[package]
name = "mekhala"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
k256 = { version = "0.13", features = ["schnorr", "serde", "ecdh"] }
sha2 = "0.10"
hex = "0.4"
getrandom = { version = "0.2", features = ["js"] }
console_error_panic_hook = "0.1.7"
futures-util = "0.3"
aes = "0.8"
cbc = "0.1"
block-padding = "0.3"
cipher = "0.4"
base64 = "0.22"
url = "2.5"
rand = "0.8"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1
