name = "mekhala"
main = "build/worker/shim.mjs"
compatibility_date = "2026-04-25"

[vars]
WALLET_REGION = "apac"

[[durable_objects.bindings]]
name = "NWC_RELAY"
class_name = "NwcRelay"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NwcRelay"]

[build]
command = "./build.sh"
watch_dir = "src"
