name = "nwc-edge-relay"
main = "build/worker/shim.mjs"
compatibility_date = "2026-04-23"

[vars]
RELAY_NAME = "nwc-edge-relay"
RELAY_DESCRIPTION = "A stateless public NWC relay running on Cloudflare Workers."
RELAY_PUBKEY = "6e468422c0020d52899347d4e3415c464c483a3d53716d6100c5c3b9b46e3d00"
RELAY_CONTACT = "https://github.com/kohanucha/nwc-edge-relay"
RELAY_SOFTWARE = "https://github.com/kohanucha/nwc-edge-relay"
RELAY_VERSION = "main"

[[durable_objects.bindings]]
name = "NWC_RELAY"
class_name = "NwcRelay"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NwcRelay"]

[build]
command = "./build.sh"
watch_dir = "src"
